- name: Host - Admin node
  hosts: admin
  become: yes
  tasks:
    - name: Enable maintenance on MagentoAdmin
      tags: maintenance_enable_admin
      shell: 'mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.orig && mv /etc/nginx/maintenance.conf /etc/nginx/nginx.conf && systemctl restart nginx'


- name: Host - Admin node
  hosts: admin
  become: yes
  become_user: nginx
  tasks:
    - name: Disable crontab on MagentoAdmin
      tags: disable_crontab_magento-admin
      command: 'chdir={{magento_root_dir_web}} bin/magento cron:remove'
      ignore_errors: yes ## Temporary, shoud be removed!!!

- name: Host - Admin node
  hosts: admin
  become: yes
  tasks:
    - name: Kill Magento cron processes on MagentoAdmin
      tags: kill_cron_processes
      shell: "pgrep -f 'bin/magento cron:run' | xargs -r kill -9"
      ignore_errors: yes

    - name: Step - Run JobUnlocker - Web node
      tags: run_jobunlocker
      command: 'chdir={{magento_root_dir_web}} php ./deployment/tools/Cron/JobUnlocker.php'
      ignore_errors: yes ## Temporary, shoud be removed!!!


- name: Host - Local
  hosts: 127.0.0.1
  become: yes
  tasks:
    - name: Rsync Magento root folder
      tags: rsync_magento_root
      shell: "rsync -azh --stats --delete --exclude 'var' --exclude 'pub/media' --exclude 'app/etc'  {{magento_root_dir_web}}/ root@{{admin_ip}}:{{magento_root_dir_web}}/"

    - name: Rsync view_preprocessed
      tags: rsync_view_preprocessed
      shell: "rsync -azh --stats --delete   {{magento_root_dir_web}}/var/view_preprocessed/ root@{{admin_ip}}:{{magento_root_dir_web}}/var/view_preprocessed/"
