- name: Host
  hosts: 127.0.0.1
  become: yes
  tasks:
#-------------------------- Git checkout ----------------------------------
    - name: Unmount EFS
      tags: unmount_efs
      mount: path={{efs_mount_point}} state=unmounted

    - name: Check unmount
      tags: unmount_check
      shell: "mount -l | grep {{efs_mount_point}}"
      register: check_result
      failed_when: efs_mount_point in check_result.stdout

    - name: Unlink 'var' 'media' 'etc' if exists
      tags: unlink_share
      file: path={{item}} state=absent
      loop:
        - '{{magento_root_dir_build}}/app/etc'
        - '{{magento_root_dir_build}}/var'
        - '{{magento_root_dir_build}}/pub/media'

    - name: Clean mount folders
      tags: clean_mount_folders
      file: path={{item}} state=absent
      loop:
        - '{{magento_root_dir_build}}/pub/media'
        - '{{magento_root_dir_build}}/var'
        - '{{magento_root_dir_build}}/app/etc'
